var topNav='';
topNav+=' <section>';
topNav+='<nav class="mainTabCtrl clearfix">';
topNav+='	<ul>';
topNav+='		<li id="Individuals"><a href="./remsCreateHostServerListing">Individuals</a><span>Individuals</span></li>';
topNav+='		<li id="All"><a href="./remsCreateHostServerListingAd">All</a><span>All</span></li>';
topNav+='	</ul>';
topNav+='</nav>';
topNav+='   </section>';
document.write(topNav);